name: CI
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: yarn
      - name: eslint
        run: yarn eslint .
      - name: Run tests in ormius-cli
        run: yarn workspace ormius-cli test
      - name: Build ormius-cli
        run: yarn workspace ormius-cli build
      - name: Run tests in ormius
        run: yarn workspace ormius test